# k8s/secrets/task-manager-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: taskmanager-node-dev
type: Opaque
stringData:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  RABBITMQ_USER: YWRtaW4=
  RABBITMQ_PASSWORD: YWRtaW4=
