apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  namespace: taskmanager-node-dev
spec:
  selector:
    app: task-manager
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
