# Comando para el despliegue y agrupación por proyecto 
# docker compose -p taskmanager-node up -d

services:
  # ---------------------------------------------------
  # RabbitMQ (broker de colas) con UI web
  # ---------------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management                   # Incluye interfaz web
    container_name: rabbitmq-task
    ports:
      - "5672:5672"                                # Puerto para conexión desde apps
      - "15672:15672"                              # Interfaz web http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # ---------------------------------------------------
  # PostgreSQL (base de datos principal del sistema)
  # ---------------------------------------------------
  postgres:
    image: postgres:15                             # Imagen oficial de PostgreSQL
    container_name: postgres-task
    ports:
      - "5432:5432"                                # Puerto por defecto de PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data     # Persistencia de datos

  # ---------------------------------------------------
  # MongoDB (Guardar los eventos fallidos al publicar)
  # ---------------------------------------------------
  mongodb-failed:
    image: mongo:6
    container_name: mongodb-task-failed-event
    ports:
      - "27017:27017"
    volumes:
      - mongo_failed_data:/data/db

  # ---------------------------------------------------
  # MongoDB (Guardar los logs de los eventos realizados)
  # ---------------------------------------------------
  mongodb-logger:
    image: mongo:6
    container_name: mongodb-task-logger
    ports:
      - "27018:27017"
    volumes:
      - mongo_logger_data:/data/db

  # ---------------------------------------------------
  # Redis (almacenamiento en memoria - usado como cache o cola ligera)
  # ---------------------------------------------------
  redis:
    image: redis:7
    container_name: redis-task
    ports:
      - "6379:6379"

# ---------------------------------------------------
# Volúmenes persistentes
# ---------------------------------------------------
volumes:
  postgres_data:
  mongo_failed_data:
  mongo_logger_data:
