# Define las credenciales del usuario de RabbitMQ como secretos de Kubernetes

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: taskmanager-node-dev   # Namespace donde se desplegará
  labels:
    app: rabbitmq
type: Opaque
data:
  rabbitmq-username: YWRtaW4=     # admin (codificado en base64)
  rabbitmq-password: YWRtaW4= # admin (codificado en base64)
