# Secret para guardar el usuario y la contraseña de PostgreSQL en base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret                     # Nombre del Secret
  namespace: taskmanager-node-dev
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=               # 'postgres' codificado en base64
  postgres-password: cG9zdGdyZXM=           # 'postgres' codificado en base64
