# Servicio para exponer PostgreSQL al exterior del clúster (desde tu host)
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: taskmanager-node-dev
spec:
  selector:
    app: postgres                         # Conecta con los pods que tienen esta etiqueta
  ports:
    - protocol: TCP
      port: 5432                          # Puerto interno del clúster
      targetPort: 5432                    # Puerto del contenedor
      nodePort: 31432                     # Puerto en el host (fuera del clúster)
  type: NodePort                          # Permite acceso desde el host (localhost:31432)
